import Decimal from 'decimal.js'
import { NFT_CATEGORIES, type Artist, type Nft, type NftCategory, type NftEdition } from '@/domains/catalog'
import { createRandom } from '../infra/random'
import { derivePricing } from '../contexts/catalog/pricing'

/** Artwork files are generated by `scripts/generate-art.mjs` into `public/art`. */
export const NFT_COUNT = 48

const NAMES = [
  'Distant Galaxy', 'Life On Edena', 'Astrofiction', 'Space Walking', 'Dancing Robots', 'Cherry Blossom',
  'Neon Tide', 'Magic Mushrooms', 'Desert Mirage', 'Orbital Bloom', 'Glass Garden', 'Silent Signal',
  'Pixel Monk', 'Solar Choir', 'Lunar Arcade', 'Paper Comet', 'Velvet Storm', 'Hollow Crown',
  'Chrome Koi', 'Midnight Atlas', 'Quiet Reactor', 'Ember Valley', 'Polar Echo', 'Saffron Drift',
  'Static Bloom', 'Copper Moon', 'Wild Circuit', 'Ivory Wave', 'Hidden Harbor', 'Prism Runner',
  'Golden Hour', 'Signal Lost', 'Ocean Code', 'Tiny Planets', 'Cobalt Dream', 'Velours',
  'Aurora Gate', 'Fractal Fern', 'Night Bazaar', 'Crystal Keys', 'Ghost Track', 'Emerald City',
  'Analog Sunset', 'Rose Machine', 'Thunder Bay', 'Moss Temple', 'Indigo Rain', 'Final Frame',
]

const ARTISTS: Artist[] = [
  { id: 'art_orbitian', name: 'Orbitian', avatarUrl: '/art/artist-1.svg' },
  { id: 'art_moondancer', name: 'Moondancer', avatarUrl: '/art/artist-2.svg' },
  { id: 'art_nebulakid', name: 'NebulaKid', avatarUrl: '/art/artist-3.svg' },
  { id: 'art_animakid', name: 'Animakid', avatarUrl: '/art/artist-4.svg' },
  { id: 'art_robotica', name: 'Robotica', avatarUrl: '/art/artist-5.svg' },
  { id: 'art_keepitreal', name: 'Keepitreal', avatarUrl: '/art/artist-6.svg' },
  { id: 'art_dishamodi', name: 'DigiLab', avatarUrl: '/art/artist-7.svg' },
  { id: 'art_ghiblier', name: 'GravityOne', avatarUrl: '/art/artist-8.svg' },
]

const COLLECTIONS = ['Genesis', 'Afterglow', 'Signals', 'Deep Field', 'Analog Futures', 'Bloom']
const BASE_PRICES = ['0.05', '0.08', '0.12', '0.15', '0.25', '0.33', '0.5', '0.75', '1.2', '1.5', '2.25', '3.1']
const TAGS = ['generativo', '3D', 'animado', 'edição limitada', 'áudio', 'pixel art', 'abstrato', 'retrato']

const EDITION_TEMPLATES = [
  { suffix: 'standard', name: 'Standard', multiplier: '1', supply: 25, maxPerOrder: 5 },
  { suffix: 'rare', name: 'Rare', multiplier: '2.5', supply: 8, maxPerOrder: 2 },
  { suffix: 'legendary', name: 'Legendary', multiplier: '6', supply: 1, maxPerOrder: 1 },
] as const

const pad = (n: number) => String(n).padStart(3, '0')

export function buildNftFixtures(): Nft[] {
  const random = createRandom(20260115)
  const baseDate = Date.UTC(2026, 0, 15)

  return NAMES.slice(0, NFT_COUNT).map((name, index) => {
    const n = index + 1
    const id = `nft_${pad(n)}`
    const category: NftCategory = NFT_CATEGORIES[index % NFT_CATEGORIES.length] as NftCategory
    const artist = ARTISTS[index % ARTISTS.length] as Artist
    const basePrice = random.pick(BASE_PRICES)
    const editionCount = 1 + (index % 3)
    const fullySoldOut = index % 11 === 5
    const hasUnavailableEdition = index % 7 === 3

    const editions: NftEdition[] = EDITION_TEMPLATES.slice(0, editionCount).map((template, editionIndex) => {
      const price = new Decimal(basePrice).times(template.multiplier).toFixed(18)
      const sold = random.int(0, Math.max(0, template.supply - 1))
      let available = template.supply - sold
      // A few low-stock editions to exercise quantity limits.
      if (editionIndex === 0 && index % 5 === 2) available = 2
      if (fullySoldOut) available = 0
      const unavailable = hasUnavailableEdition && editionIndex === editionCount - 1 && editionCount > 1
      return {
        id: `${id}_${template.suffix}`,
        name: template.name,
        price,
        supply: template.supply,
        available: unavailable ? 0 : available,
        maxPerOrder: template.maxPerOrder,
        status: unavailable ? 'unavailable' : available > 0 ? 'available' : 'sold_out',
      }
    })

    const image = {
      src: `/art/nft-${pad(n)}-1.svg`,
      alt: `${name}, obra digital de ${artist.name}`,
      width: 600,
      height: 600,
    }

    const nft: Nft = {
      id,
      name,
      artist,
      category,
      image,
      featured: n <= 3,
      createdAt: new Date(baseDate - index * 36 * 3600 * 1000).toISOString(),
      version: 1,
      description: `${name} faz parte da coleção ${COLLECTIONS[index % COLLECTIONS.length]} de ${artist.name}. Cada edição é registrada on-chain e acompanha o arquivo original em alta resolução.`,
      collection: COLLECTIONS[index % COLLECTIONS.length] as string,
      tags: [TAGS[index % TAGS.length] as string, TAGS[(index + 3) % TAGS.length] as string],
      gallery: [1, 2, 3].map((view) => ({
        src: `/art/nft-${pad(n)}-${view}.svg`,
        alt: view === 1 ? image.alt : `${name}, detalhe ${view - 1} da obra`,
        width: 600,
        height: 600,
      })),
      editions,
      priceFrom: '0',
      totalAvailable: 0,
    }
    return { ...nft, ...derivePricing(nft.editions) }
  })
}
